export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROPERTIES: '/properties',
  WHATSAPP: '/whatsapp',
  CLIENTS: '/clients',
  APPOINTMENTS: '/appointments',
  NETWORK: '/network',
  BUSINESS_POSTS: '/business-posts',
  MARKETING: '/marketing',
  AGREEMENTS: '/agreements',
  PROJECTS: '/projects',
} as const;
