export const ROUTES = {
  HOME: '/',
  FAQ: '/faq',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PROPERTIES: '/properties',
  SMS_MARKETING: '/sms-marketing',
  CLIENTS: '/clients',
  APPOINTMENTS: '/appointments',
  NETWORK: '/network',
  BUSINESS_POSTS: '/business-posts',
  STAFF: '/staff',
  MARKETING: '/marketing',
  AGREEMENTS: '/agreements',
  PROJECTS: '/projects',
  BUILDING_DATA: '/building-data',
  ANALYTICS: '/analytics',
  LEADS: '/leads',

  // Profile & Settings Routes
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  
  // Subscription Routes
  PRICING: '/pricing',
  SUBSCRIPTION: '/subscription',
  SUBSCRIPTION_ACTIVATE_TRIAL: '/subscription/activate-trial',
  SUBSCRIPTION_CHECKOUT: '/subscription/checkout/:planId',
  SUBSCRIPTION_SUCCESS: '/subscription/success',

  // Admin Routes
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_REVENUE: '/admin/revenue',
  ADMIN_SMS: '/admin/sms',
  ADMIN_DOWNLOAD: '/admin/download',
  ADMIN_ANNOUNCEMENTS: '/admin/announcements',
  ADMIN_FEEDBACK: '/admin/feedback',
  ADMIN_ACTIVITY: '/admin/activity',
  ADMIN_RENEWALS: '/admin/renewals',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_STORAGE: '/admin/storage',
  ADMIN_CONFIG: '/admin/config',
} as const;
