import { BusinessPost } from '../../types';

export const mockPosts: BusinessPost[] = [
  {
    id: '1',
    title: 'Premium Office Furniture Set — Complete Setup',
    category: 'furniture_office',
    subcategory: 'sale',
    description: 'Complete office furniture set including executive desk, ergonomic chairs, filing cabinets, and conference table. Excellent condition, barely used.',
    price: 125000,
    images: ['https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg'],
    location: 'Whitefield, Bangalore',
    contact_info: { name: 'Priya Sharma', phone: '+91 98765 43211' },
    user_id: '2',
    status: 'active',
    created_at: '2024-01-14T15:20:00Z',
    updated_at: '2024-01-14T15:20:00Z',
  },
  {
    id: '2',
    title: 'Modular Kitchen and Home Furniture for Sale',
    category: 'furniture_house',
    subcategory: 'sale',
    description: 'Complete modular kitchen setup with chimney and hob. Also includes bedroom furniture and dining set.',
    price: 175000,
    images: ['https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg'],
    location: 'Pune, Maharashtra',
    contact_info: { name: 'Anjali Menon', phone: '+91 98765 43215', email: 'anjali@example.com' },
    user_id: '6',
    status: 'active',
    created_at: '2024-01-10T14:00:00Z',
    updated_at: '2024-01-10T14:00:00Z',
  },
  {
    id: '3',
    title: 'Experienced Real Estate Sales Manager Required',
    category: 'staff',
    subcategory: 'requirement',
    description: 'Looking for an experienced sales manager with 5+ years in real estate. Must have proven track record and excellent communication skills.',
    price: 50000,
    images: [],
    location: 'Mumbai, Maharashtra',
    contact_info: { name: 'Amit Patel', phone: '+91 98765 43212', email: 'amit@realty.com' },
    user_id: '3',
    status: 'active',
    created_at: '2024-01-13T09:45:00Z',
    updated_at: '2024-01-13T09:45:00Z',
  },
  {
    id: '4',
    title: 'Rajesh Rent Agreement Services',
    category: 'vendor',
    subcategory: 'rent_agreement',
    description: 'Professional rent agreement drafting and registration. Serving Koramangala, Indiranagar, and HSR Layout. Quick turnaround, legally compliant documents.',
    images: [],
    location: 'Koramangala, Bangalore',
    contact_info: {
      name: 'Rajesh Kumar',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      address: '12, 5th Cross, Koramangala, Bangalore',
    },
    rating: 4,
    user_id: '4',
    status: 'active',
    created_at: '2024-01-12T11:15:00Z',
    updated_at: '2024-01-12T11:15:00Z',
  },
  {
    id: '5',
    title: 'CleanHome — Flat Cleaning Services',
    category: 'vendor',
    subcategory: 'flat_cleaner',
    description: 'Professional flat and home cleaning services. Deep cleaning, move-in/move-out cleaning. Serving South Delhi and surrounding areas.',
    images: [],
    location: 'South Delhi, Delhi',
    contact_info: {
      name: 'Vikram Singh',
      phone: '+91 98765 43214',
      whatsapp: '+91 98765 43214',
    },
    rating: 5,
    user_id: '5',
    status: 'active',
    created_at: '2024-01-11T16:30:00Z',
    updated_at: '2024-01-11T16:30:00Z',
  },
  {
    id: '6',
    title: 'Property Documentation Specialist Needed',
    category: 'staff',
    subcategory: 'requirement',
    description: 'Seeking experienced documentation specialist for real estate transactions. Knowledge of legal procedures essential.',
    price: 35000,
    images: [],
    location: 'Chennai, Tamil Nadu',
    contact_info: { name: 'Rahul Verma', phone: '+91 98765 43216' },
    user_id: '7',
    status: 'active',
    created_at: '2024-01-09T10:20:00Z',
    updated_at: '2024-01-09T10:20:00Z',
  },
  {
    id: '7',
    title: 'GreenShield Pest Control',
    category: 'vendor',
    subcategory: 'pest_controller',
    description: 'Certified pest control services for residential and commercial properties. Cockroach, termite, rodent, and mosquito treatments. Serving Pune and PCMC areas.',
    images: [],
    location: 'Pune, Maharashtra',
    contact_info: {
      name: 'Suresh Patil',
      phone: '+91 98765 43220',
      whatsapp: '+91 98765 43220',
      address: 'Shop 4, Pimpri Market, Pune',
    },
    rating: 4,
    user_id: '8',
    status: 'active',
    created_at: '2024-01-08T13:45:00Z',
    updated_at: '2024-01-08T13:45:00Z',
  },
  {
    id: '8',
    title: 'FurnishEase — Furniture on Rent',
    category: 'furniture_house',
    subcategory: 'rent',
    description: 'Rent quality home furniture — beds, sofas, dining sets, washing machines. Flexible monthly plans. Serving Hyderabad.',
    price: 3500,
    images: [],
    location: 'Hyderabad, Telangana',
    contact_info: { name: 'Kavita Joshi', phone: '+91 98765 43217', email: 'kavita@furnishease.com' },
    user_id: '9',
    status: 'active',
    created_at: '2024-01-07T10:00:00Z',
    updated_at: '2024-01-07T10:00:00Z',
  },
];
